[package]
name = "uring-playground"
version = "0.1.0"
edition = "2021"

[lints.clippy]
future_not_send = { level = "allow", priority = 1 }

all = "deny"
pedantic = "warn"
nursery = "warn"

[dependencies]
io-uring = "0.6"
slab = "0.4"

noop-waker = "0.1"
async-task = "4"

tokio = "1"
libc = "0.2"
socket2 = "0.5"
