[package]
name = "uring-playground"
version = "0.1.0"
edition = "2021"

[lints.clippy]
all = "deny"
pedantic = "warn"
nursery = "warn"


[dependencies]
io-uring = "0.6"
slab = "0.4"

noop-waker = "0.1"
async-task = "4"

futures-io = "0.3"
libc = "0.2"
